import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Authprovider from "./authprovider/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Product Compare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <Authprovider>
        <body
          className={`${inter.className} h-full flex flex-col min-h-screen`}
        >
          <Header />
          <section className="flex-1 mt-20 mb-20">{children}</section>
          <Footer />
        </body>
      </Authprovider>
    </html>
  );
}
